---
title: "git_01"
author: "Nikki Gordon"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
A boat beneath a sunny sky,  
Lingering onward dreamily  
In an evening of July —  
  
Children three that nestle near,  
Eager eye and willing ear,  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Some say the world will end in fire,  
Some say in ice.  
From what I’ve tasted of desire  
I hold with those who favor fire.  
But if it had to perish twice,  
  
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
“The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright —  
And this was odd, because it was  
The middle of the night.  
  
The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done —  
“It’s very rude of him,” she said,  
“To come and spoil the fun.”  
  
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
When Miep took us home with her  
She held us up in the air,  
  
Eye-level with those eyes  
You may know, eyes spelling  
  
Sorrow-girl, wait-for-me,  
Happiness-around-a-corner-  
  
One-day, hurry-back, don’t-tell.  
Two new hands took us in,  
  
Skin cradling skin.  
How empty we had been,  
  
Only a little bit worn —  
Not a penny, not a pebble  
  
Dwelling within.  
We became an altar,  